ekf_filter_node:
  ros__parameters:

    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Wheel Odometry (position + linear velocity only)
    odom0: /diff_cont/odom
    odom0_config: [true,  true,  false,   # x, y
                   false, false, false,   # roll, pitch, yaw (disabled)
                   true,  false, false,   # vx
                   false, false, false,   # vroll, vpitch, vyaw
                   false, false, false]

    # IMU (Yaw + angular velocity)
    imu0: /imu/data
    imu0_config: [false, false, false,
                  false, false, true,     # yaw
                  false, false, false,
                  false, false, true,     # vyaw
                  false, false, false]

    imu0_remove_gravitational_acceleration: true